const { isFloat, convertFloatToCommaString } = require('./convert-float-to-string');
const { convertJSONToCSV } = require('./convert-json-to-csv');
const { formatCpfCnpj } = require('./format-cpf-cnpj');
const { isDate, convertDateFormat } = require('./verify-and-convert-dates');

const compareJson = () => {



    let snirhJson = {
        "INT_CD": "928338",
        "INT_TIN_DS": "Captação",
        "INT_TIN_CD": "1",
        "INT_TSU_DS": "Superficial",
        "INT_TSU_CD": "1",
        "INT_TCH_CD": "1",
        "INT_TCH_DS": "Rio ou Curso D'Água",
        "INT_TSI_DS": "Operação",
        "INT_TSI_CD": "3",
        "INT_TOD_DS": "ETL - Importação de Dados dos Estados",
        "INT_TOD_CD": "4",
        "INT_TDM_DS": "Estadual",
        "INT_TDM_CD": "1",
        "INT_NU_CNARH": "710002572992",
        "INT_NU_SIAGAS": "",
        "INT_NU_LATITUDE": "-15.960674",
        "INT_NU_LONGITUDE": "-47.38104",
        "ING_NU_IBGEMUNICIPIO": "5300108",
        "ING_SG_UFMUNICIPIO": "DF",
        "ING_NM_MUNICIPIO": "BRASÍLIA",
        "INT_NM_CORPOHIDRICO": "",
        "INT_NM_CORPOHIDRICOALTERADO": "",
        "INT_DS_ORGAO": "ADASA",
        "INT_CD_ORGAO": "53",
        "INT_CD_INTERFERENCIAORIGINAL": "",
        "INT_DT_REGISTRO": "2019-01-21",
        "INT_CD_DECLARACAO": "",
        "INT_CD_ORIGEM": "",
        "INT_DS_OPCIONAL": "",
        "EMP_NM_EMPREENDIMENTO": "DF 100 KM 23 LOTE 10 A 1427 A 29 FAZENDA CANADÁ",
        "EMP_NM_USUARIO": "MARIZA STUANI DE ALMEIDA MATSUI",
        "EMP_NU_CPFCNPJ": "89746236687",
        "EMP_DS_EMAILRESPONSAVEL": "",
        "EMP_NU_CEPENDERECO": "",
        "EMP_CD_IBGEMUNCORRESPONDENCIA": "",
        "EMP_DS_LOGRADOURO": "",
        "EMP_DS_COMPLEMENTOENDERECO": "",
        "EMP_NU_LOGRADOURO": "",
        "EMP_NU_CAIXAPOSTAL": "",
        "EMP_DS_BAIRRO": "",
        "EMP_NU_DDD": "",
        "EMP_NU_TELEFONE": "",
        "EMP_SG_UF": "",
        "EMP_NM_MUNICIPIO": "",
        "OUT_TP_OUTORGA": "Direito de Uso",
        "OUT_TPO_CD": "1",
        "OUT_TP_SITUACAOOUTORGA": "Outorgado",
        "OUT_TSP_CD": "1",
        "OUT_DT_OUTORGAFINAL": "2023-08-22",
        "OUT_DT_OUTORGAINICIAL": "2018-08-22",
        "OUT_NU_PROCESSO": "197000003752018",
        "OUT_TP_ATO": "DESPACHO",
        "OUT_NU_ATO": "7312018",
        "DAD_QT_VAZAODIAJAN": "0",
        "DAD_QT_VAZAODIAFEV": "0",
        "DAD_QT_VAZAODIAMAR": "0",
        "DAD_QT_VAZAODIAABR": "0",
        "DAD_QT_VAZAODIAMAI": "151.2",
        "DAD_QT_VAZAODIAJUN": "151.2",
        "DAD_QT_VAZAODIAJUL": "151.2",
        "DAD_QT_VAZAODIAAGO": "151.2",
        "DAD_QT_VAZAODIASET": "151.2",
        "DAD_QT_VAZAODIAOUT": "151.2",
        "DAD_QT_VAZAODIANOV": "0",
        "DAD_QT_VAZAODIADEZ": "0",
        "DAD_QT_HORASJAN": "0",
        "DAD_QT_HORASFEV": "0",
        "DAD_QT_HORASMAR": "0",
        "DAD_QT_HORASABR": "0",
        "DAD_QT_HORASMAI": "21",
        "DAD_QT_HORASJUN": "21",
        "DAD_QT_HORASJUL": "21",
        "DAD_QT_HORASAGO": "21",
        "DAD_QT_HORASSET": "21",
        "DAD_QT_HORASOUT": "21",
        "DAD_QT_HORASNOV": "0",
        "DAD_QT_HORASDEZ": "0",
        "DAD_QT_DIAJAN": "0",
        "DAD_QT_DIAFEV": "0",
        "DAD_QT_DIAMAR": "0",
        "DAD_QT_DIAABR": "0",
        "DAD_QT_DIAMAI": "31",
        "DAD_QT_DIAJUN": "30",
        "DAD_QT_DIAJUL": "31",
        "DAD_QT_DIAAGO": "31",
        "DAD_QT_DIASET": "30",
        "DAD_QT_DIAOUT": "31",
        "DAD_QT_DIANOV": "0",
        "DAD_QT_DIADEZ": "0",
        "INT_QT_VAZAOMAXIMA": "151.2",
        "INT_QT_VAZAOMEDIA": "75.6",
        "INT_QT_VOLUMEANUAL": "584236.8",
        "FIN_TFN_DS": "Irrigação",
        "FIN_TFN_CD": "5",
        "FES_NU_PROFUNDIDADEMEDIATANQUE": "",
        "FES_NU_AREATOTALTANQUE": "",
        "TTC_TCU_DS": "",
        "TTC_TCU_CD": "",
        "FSE_TES_DS": "",
        "FSE_TES_CD": "",
        "FIE_NU_POPULACAOFINALATENDIDA": "",
        "FIE_TPS_DS": "",
        "FIE_TPS_CD": "",
        "FAH_TAH_DS": "",
        "FAH_TAH_CD": "",
        "FAH_NU_POTENCIAINSTALADA": "",
        "FAH_IC_APROVEITAMENTOFIODAGUA": "",
        "FAH_NU_AREAINUNDADANA": "",
        "FAH_NU_VOLUMENA": "",
        "FPE_TPE_DS": "",
        "FPE_TPE_CD": "",
        "FPE_CNA_CD": "",
        "IUS_NU_ALTURARES": "",
        "IUS_NU_AREARESMAX": "",
        "IUS_NU_VOLUMERES": "",
        "IUS_NU_PERCENTUALRETORNO": "0",
        "IUS_NM_ENTIDADECONCEDENTE": "",
        "IUS_NU_CONCESSAO": "",
        "IUS_DT_FINALCONCESSAO": "",
        "ETP_MPE_DS": "",
        "ETP_MPE_CD": "",
        "ETP_NU_QUANTIDADEMAXMENSAL": "",
        "SIR_TSI_DS": "Aspersão por sistema convencional",
        "SIR_TSI_CD": "3",
        "SIR_TCT_DS": "Hortaliças",
        "SIR_TCT_CD": "1120",
        "SIR_NU_AREAIRRIGADA": "150",
        "FIA_NU_POPULACAOATENDIDA": "",
        "FTE_NU_POTENCIAINSTALADA": "",
        "FTE_NU_PRODUCAOMENSALMEDIA": "",
        "FTE_TCO_DS": "",
        "FTE_TCO_CD": "",
        "FEA_NU_PRODUCAOMAXMENSALAREIA": "",
        "FEA_NU_PROPORCAOAGUAPOLPA": "",
        "FEA_PC_TEORUMIDADE": "",
        "FOH_TOH_DS": "",
        "FOH_TOH_CD": "",
        "FRE_NU_AREAINUNDADANA": "",
        "FRE_NU_VOLUMENA": "",
        "FOU_TOU_DS": "",
        "FOU_TOU_CD": "",
        "HTE_NU_QUANTIDADE": "",
        "TUC_TEC_DS": "",
        "TUC_TEC_CD": "",
        "TUC_DS": "",
        "TUC_CD": "",
        "FTR_AR_TOTALEMPREENDIMENTO": "",
        "FTR_NU_PROCESSOMPA": "",
        "ESC_NU_PRODUCAOPRETENDIDA": "",
        "ESC_TET_DS": "",
        "ESC_TET_CD": "",
        "CTE_TSC_DS": "",
        "CTE_TSC_CD": "",
        "CTE_TCA_DS": "",
        "CTE_TCA_CD": "",
        "CTE_NU_CABECAS": "",
        "EFL_NU_DBOBRUTO": "",
        "EFL_NU_DBOTRATADO": "",
        "EFL_NU_FOSFOROBRUTO": "",
        "EFL_NU_FOSFOROTRATADO": "",
        "EFL_NU_NITROGENIOBRUTO": "",
        "EFL_NU_NITROGENIOTRATADO": "",
        "EFL_NU_TEMPERATURA": "",
        "EFL_TTE_DS": "",
        "EFL_TTE_CD": "",
        "ITC_TUM_DS": "",
        "ITC_TUM_CD": "",
        "ITC_NU_PRODUCAOANUAL": "",
        "CNA_DS": "",
        "CNA_CD_CNAE": "",
        "ASB_DT_INSTALACAO": "",
        "ASB_TNP_DS": "",
        "ASB_TNP_CD": "",
        "ASB_NU_DIAMETROPERFURACAO": "",
        "ASB_NU_DIAMETROFILTRO": "",
        "ASB_AQP_DS": "",
        "ASB_AQP_CD": "",
        "ASB_NU_TOPO": "",
        "ASB_NU_BASE": "",
        "ASB_TPN_DS": "",
        "ASB_TPN_CD": "",
        "ABS_TCA_DS": "",
        "ABS_TCA_CD": "",
        "ASB_NU_PROFUNDIDADEFINAL": "",
        "ASB_NU_ALTURABOCATUBO": "",
        "ASB_NU_COTATERRENO": "",
        "TST_DT": "",
        "TST_TTB_DS": "",
        "TST_TTB_CD": "",
        "TST_DS_TEMPODURACAO": "",
        "TST_NU_ND": "",
        "TST_NU_NE": "",
        "TST_VZ_ESTABILIZACAO": "",
        "TST_TMI_DS": "",
        "TST_TMI_CD": "",
        "TST_NU_COEFICIENTEARMAZENAMENT": "",
        "TST_NU_TRANSMISSIVIDADE": "",
        "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
        "TST_NU_PERMEABILIDADE": "",
        "AMA_DT_COLETA": "",
        "AMA_DT_ANALISE": "",
        "AMA_NU_CONDUTIVIDADEELETRICA": "",
        "AMA_QT_TEMPERATURA": "",
        "AMA_QT_STD": "",
        "AMA_QT_PH": "",
        "AMA_QT_COLIFORMESTOTAIS": "",
        "AMA_QT_COLIFORMESFECAIS": "",
        "AMA_QT_BICARBONATO": "",
        "AMA_QT_CALCIO": "",
        "AMA_QT_CARBONATO": "",
        "AMA_QT_CLORETO": "",
        "AMA_QT_DUREZATOTAL": "",
        "AMA_QT_FERROTOTAL": "",
        "AMA_QT_FLUORETOS": "",
        "AMA_QT_NITRATOS": "",
        "AMA_QT_NITRITOS": "",
        "AMA_QT_POTASSIO": "",
        "AMA_QT_SODIO": "",
        "AMA_QT_SULFATO": "",
        "AMA_QT_MAGNESIO": "",
        "DATA_EXTRACAO": "2024-07-01",
        "ING_CD_OTTOBACIA_TRECHO": "7684921",
        "ING_CD_COMITEFEDERAL": "7",
        "ING_NM_COMITEFEDERAL": "São Francisco",
        "ING_CD_COMITEESTADUAL": "159",
        "ING_NM_COMITEESTADUAL": "CBH dos Afluentes do Rio Preto",
        "ING_CS_CONAMA": "",
        "": "\n                            <div class=\"div-btn flex flex-row justify-around w-24 min-w-24 max-w-24\">\n                                <!-- select button -->\n                                <button id=\"btn-snirh-selection\" class=\"hover:bg-sky-600 active:bg-sky-700 focus:outline-none focus:ring focus:ring-sky-300\">\n                                    <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"w-6 h-6\">\n                                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z\" />\n                                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z\" />\n                                    </svg>\n                                </button>\n                                <!-- copy button -->\n                                <button class=\"hover:bg-sky-600 active:bg-sky-700 focus:outline-none focus:ring focus:ring-sky-300\">\n                                    <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\n                                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"m4.5 12.75 6 6 9-13.5\" />\n                                    </svg>\n                                </button>\n                            </div>"
    }

    let id = snirhJson.INT_CD
    console.log('snirh id: ', id)

    //convertJSONToCSV(snirhJson, './backend/data/csv/test-1/edicao-snirh.csv')

    let adasa = {
        "INT_CD": "",
        "INT_CD_ORIGEM": "221",
        "INT_DS_OPTIONAL": "",
        "INT_TIN_CD": "1",
        "INT_TSU_CD": "1",
        "INT_NU_SIAGAS": "",
        "INT_NU_LATITUDE": "-15,960674",
        "INT_NU_LONGITUDE": "-47,381040",
        "INT_NM_CORPOHIDRICOALTERADO": "",
        "EMP_NM_EMPREENDIMENTO": "DF 100, KM 23, LOTE 10 A 14/27 A 29, FAZENDA CANADÁ",
        "EMP_NM_RESPONSAVEL": "MARIZA STUANI DE ALMEIDA MATSUI",
        "EMP_NU_CPFCNPJ": "#89746236687",
        "EMP_DS_EMAILRESPONSAVEL": "naoinformado@gmail.com.br",
        "EMP_NU_CEPENDERECO": "71570000",
        "EMP_DS_LOGRADOURO": "DF 100, KM 23, LOTE 10 A 14/27 A 29, FAZENDA CANADÁ,",
        "EMP_DS_COMPLEMENTOENDERECO": "",
        "EMP_NU_LOGRADOURO": "",
        "EMP_NU_CAIXAPOSTAL": "",
        "EMP_DS_BAIRRO": "ITAPETI",
        "EMP_NU_DDD": "DF",
        "EMP_NU_TELEFONE": "6135011006",
        "EMP_CD_IBGEMUNCORRESPONDENCIA": "5300108",
        "OUT_TP_OUTORGA": "1",
        "OUT_TP_SITUACAOOUTORGA": "4",
        "OUT_DT_OUTORGAINICIAL": "22/08/2018",
        "OUT_DT_OUTORGAFINAL": "22/08/2028",
        "OUT_NU_PROCESSO": "19700000375/2018",
        "OUT_TP_AT": "DESPACHO",
        "OUT_NU_ATO": "731/2018",
        "DAD_QT_VAZAODIAJAN": "0,0",
        "DAD_QT_VAZAODIAFEV": "0,0",
        "DAD_QT_VAZAODIAMAR": "0,0",
        "DAD_QT_VAZAODIAABR": "0,0",
        "DAD_QT_VAZAODIAMAI": "151,2",
        "DAD_QT_VAZAODIAJUN": "151,2",
        "DAD_QT_VAZAODIAJUL": "151,2",
        "DAD_QT_VAZAODIAAGO": "151,2",
        "DAD_QT_VAZAODIASET": "151,2",
        "DAD_QT_VAZAODIAOUT": "151,2",
        "DAD_QT_VAZAODIANOV": "0,0",
        "DAD_QT_VAZAODIADEZ": "0,0",
        "DAD_QT_HORASJAN": "0",
        "DAD_QT_HORASFEV": "0",
        "DAD_QT_HORASMAR": "0",
        "DAD_QT_HORASABR": "0",
        "DAD_QT_HORASMAI": "21",
        "DAD_QT_HORASJUN": "21",
        "DAD_QT_HORASJUL": "21",
        "DAD_QT_HORASAGO": "21",
        "DAD_QT_HORASSET": "21",
        "DAD_QT_HORASOUT": "21",
        "DAD_QT_HORASNOV": "0",
        "DAD_QT_HORASDEZ": "0",
        "DAD_QT_DIAJAN": "0",
        "DAD_QT_DIAFEV": "0",
        "DAD_QT_DIAMAR": "0",
        "DAD_QT_DIAABR": "0",
        "DAD_QT_DIAMAI": "31",
        "DAD_QT_DIAJUN": "30",
        "DAD_QT_DIAJUL": "31",
        "DAD_QT_DIAAGO": "31",
        "DAD_QT_DIASET": "30",
        "DAD_QT_DIAOUT": "31",
        "DAD_QT_DIANOV": "0",
        "DAD_QT_DIADEZ": "0",
        "FIN_CD": "0",
        "FIN_TFN_CD": "5",
        "FES_NU_PROFUNDIDADEMEDIATANQUE": "",
        "FES_NU_AREATOTALTANQUE": "",
        "TTC_CD": "",
        "TTC_TCU_CD": "",
        "FSE_TES_CD": "",
        "FIE_TPS_CD": "",
        "FAH_TAH_CD": "",
        "FAH_NU_POTENCIAINSTALADA": "",
        "FAH_IC_APROVEITAMENTOFIODAGUA": "",
        "FAH_NU_AREAINUNDADANA": "",
        "FAH_NU_VOLUMENA": "",
        "FPE_TPE_CD": "",
        "FPE_CNA_CD": "",
        "ETP_CD": "",
        "ETP_MPE_CD": "",
        "ETP_NU_QUANTIDADEMAXMENSAL": "",
        "IUS_NU_ALTURARES": "",
        "IUS_NU_AREARESMAX": "",
        "IUS_NU_VOLUMERES": "",
        "IUS_NM_ENTIDADECONCEDENTE": "",
        "IUS_NU_CONCESSAO": "",
        "IUS_DT_FINALCONCESSAO": "",
        "SIR_CD": "",
        "SIR_TSI_CD": "",
        "SIR_TCT_CD": "",
        "SIR_NU_AREAIRRIGADA": "",
        "FTE_NU_POTENCIAINSTALADA": "",
        "FTE_NU_PRODUCAOMENSALMEDIA": "",
        "FTE_TCO_CD": "",
        "FTE_TSR_CD": "",
        "FEA_NU_PRODUCAOMAXMENSALAREIA": "",
        "FEA_NU_PROPORCAOAGUAPOLPA": "",
        "FEA_PC_TEORUMIDADE": "",
        "FOH_TOH_CD": "",
        "FRE_NU_AREAINUNDADANA": "",
        "FRE_NU_VOLUMENA": "",
        "OTO_TOU_CD": "",
        "OTO_CD": "",
        "OTO_NM_OUTROUSO": "",
        "OTO_DS_OUTROUSO": "",
        "HTE_CD": "",
        "HTE_NU_QUANTIDADE": "",
        "TUC_TEC_CD": "",
        "TUC_CD": "",
        "FTR_AR_TOTALEMPREENDIMENTO": "",
        "ESC_CD": "",
        "ESC_NU_PRODUCAOPRETENDIDA": "",
        "ESC_TET_CD": "",
        "CTE_CD": "",
        "CTE_TSC_CD": "",
        "CTE_TCA_CD": "",
        "CTE_NU_CABECAS": "",
        "ITC_CD": "",
        "ITC_TUM_CD": "",
        "ITC_NU_PRODUCAOANUAL": "",
        "ITC_CNA_CD": "",
        "EFL_NU_DBOBRUTO": "",
        "EFL_NU_DBOTRATADO": "",
        "EFL_NU_FOSFOROBRUTO": "",
        "EFL_NU_FOSFOROTRATADO": "",
        "EFL_NU_NITROGENIOBRUTO": "",
        "EFL_NU_NITROGENIOTRATADO": "",
        "EFL_NU_TEMPERATURA": "",
        "EFL_TTE_CD": "",
        "ASB_DT_INSTALACAO": "",
        "ASB_TNP_CD": "",
        "ASB_NU_DIAMETROPERFURACAO": "",
        "ASB_NU_DIAMETROFILTRO": "",
        "ASB_TPA_CD": "",
        "ASB_NU_TOPO": "",
        "ASB_NU_BASE": "",
        "ASB_TCQ_CD": "",
        "ASB_NU_PROFUNDIDADEFINAL": "",
        "ASB_NU_ALTURABOCATUBO": "",
        "ASB_NU_COTATERRENO": "",
        "ASB_DS_AQUIFEROEXPLOTADO": "",
        "TST_TTB_CD": "",
        "TST_DS_TEMPODURACAO": "",
        "TST_NU_ND": "",
        "TST_NU_NE": "",
        "TST_VZ_ESTABILIZACAO": "",
        "TST_TMI_CD": "",
        "TST_NU_COEFICIENTEARMAZENAMENT": "",
        "TST_NU_TRANSMISSIVIDADE": "",
        "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
        "TST_NU_PERMEABILIDADE": "",
        "AMA_DT_COLETA": "",
        "AMA_DT_ANALISE": "",
        "AMA_NU_CONDUTIVIDADEELETRICA": "",
        "AMA_QT_TEMPERATURA": "",
        "AMA_QT_STD": "",
        "AMA_QT_PH": "",
        "AMA_QT_COLIFORMESTOTAIS": "",
        "AMA_QT_COLIFORMESFECAIS": "",
        "AMA_QT_BICARBONATO": "",
        "AMA_QT_CALCIO": "",
        "AMA_QT_CARBONATO": "",
        "AMA_QT_CLORETO": "",
        "AMA_QT_DUREZATOTAL": "",
        "AMA_QT_FERROTOTAL": "",
        "AMA_QT_FLUORETOS": "",
        "AMA_QT_NITRATOS": "",
        "AMA_QT_NITRITOS": "",
        "AMA_QT_POTASSIO": "",
        "AMA_QT_SODIO": "",
        "AMA_QT_SULFATO": "",
        "AMA_QT_MAGNESIO": ""
    }

    convertJSONToCSV(adasa, './backend/data/csv/test-1/edicao-adasa.csv')

    // Cria array para formatar valores de acordo com o SNIRH.
    let adasaKeyValues = Object.entries(adasa);
   

    let objectToSend = adasa

    // VERIFICAR SE É NECESSÁRIO ESTES FILTROS E FORMATAÇÕES.
    // ESTÁ DANDO ERRO NAS LINHAS DE VAZÕES, O VALOR ESTÁ VINDO 0,00 E CONVERTENDO PARA 0. TEM QUE SER DECIMAL, => 0,00
    // Na primeira vez adiciona todos os atributos
    adasaKeyValues.forEach(([key, value]) => {

        // Converte float para string com vírgula, ex: -15.456 para -15,456
        if (isFloat(value)) {
            let str = convertFloatToCommaString(value);

            objectToSend[key] = str
            // Adiciona máscara no cnpj ou cpf, ex: #22255544489 para #222.555.444-89
        } else if (key === 'EMP_NU_CPFCNPJ') {
            let cpfCnpj = '#' + formatCpfCnpj(value);
            objectToSend[key] = cpfCnpj;

            // Verifica e converte a data 2020-05-27 para 27/05/2020
        } else if (isDate(value)) {
            let dataConverted = convertDateFormat(value)
            objectToSend[key] = dataConverted;
        }
        else {
            objectToSend[key] = value
        }


    });

    // Adiciona o id de edição.
    objectToSend.INT_CD = id;
    objectToSend.EMP_NM_RESPONSAVEL = "Teste 010624 " + objectToSend.EMP_NM_RESPONSAVEL

    convertJSONToCSV(objectToSend, './backend/data/csv/test-1/edicao-object-to-send.csv')

    console.log(objectToSend)

}


compareJson()