29/11/2024  - 13:38

"OUT_DT_FINAL": "29/11/2058",
"OUT_DT_INICIAL": "24/01/2024",
"INT_CD_ORIGEM": "14489",

"EMP_NM_USUARIO": "SILVANY CAMBRAIA RODRIGUES DINIZ",

{

    "INT_TIN_CD": "1",
    "INT_TSU_CD": "2",
    "INT_TSI_CD": "",
    "INT_CR_LATITUDE": "-15,651041",
    "INT_CR_LONGITUDE": "-48,099428",
    "ING_NU_IBGEMUNICIPIO": "5300108",
    "EMP_NM_EMPREENDIMENTO": "NÚCLEO RURAL ALEXANDRE GUSMÃO, GLEBA 01, CHÁCARA 65",
    "EMP_NU_CPFCNPJ": "#12236918615",
    "EMP_NM_USUARIO": "SILVANY CAMBRAIA RODRIGUES DINIZ",
    "EMP_DS_EMAILRESPONSAVEL": "guimarodidiz@gmail.com",
    "EMP_NU_CEPENDERECO": "70754070",
    "EMP_DS_LOGRADOURO": "SQN 111, BLOCO G, APARTAMENTO 507, ASA NORTE",
    "EMP_DS_COMPLEMENTOENDERECO": "",
    "EMP_NU_LOGRADOURO": "",
    "EMP_NU_CAIXAPOSTAL": "0",
    "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
    "EMP_NU_DDD": "61",
    "EMP_NU_TELEFONE": "999714980",
    "OUT_TPO_CD": "7",
    "OUT_TSP_CD": "4",
    "OUT_DT_FINAL": "29/11/2058",
    "OUT_DT_INICIAL": "24/01/2024",
    "OUT_NU_PROCESSO": "00197-00004781/2023-47",
    "OUT_DS_ATO": "REGISTRO DE USO",
    "OUT_NU_ATO": "1159/2024",
    "INT_NU_SIAGAS": "",
    "OPE_VZ_MESJAN": "0,24",
    "OPE_VZ_MESFEV": "0,24",
    "OPE_VZ_MESMAR": "0,24",
    "OPE_VZ_MESABR": "0,24",
    "OPE_VZ_MESMAI": "0,24",
    "OPE_VZ_MESJUN": "0,24",
    "OPE_VZ_MESJUL": "0,24",
    "OPE_VZ_MESAGO": "0,24",
    "OPE_VZ_MESSET": "0,24",
    "OPE_VZ_MESOUT": "0,24",
    "OPE_VZ_MESNOV": "0,24",
    "OPE_VZ_MESDEZ": "0,24",
    "OPE_QT_HORASJAN": "5",
    "OPE_QT_HORASFEV": "5",
    "OPE_QT_HORASMAR": "5",
    "OPE_QT_HORASABR": "5",
    "OPE_QT_HORASMAI": "5",
    "OPE_QT_HORASJUN": "5",
    "OPE_QT_HORASJUL": "5",
    "OPE_QT_HORASAGO": "5",
    "OPE_QT_HORASSET": "5",
    "OPE_QT_HORASOUT": "5",
    "OPE_QT_HORASNOV": "5",
    "OPE_QT_HORASDEZ": "5",
    "OPE_QT_DIAJAN": "31",
    "OPE_QT_DIAFEV": "29",
    "OPE_QT_DIAMAR": "31",
    "OPE_QT_DIAABR": "30",
    "OPE_QT_DIAMAI": "31",
    "OPE_QT_DIAJUN": "30",
    "OPE_QT_DIAJUL": "31",
    "OPE_QT_DIAAGO": "31",
    "OPE_QT_DIASET": "30",
    "OPE_QT_DIAOUT": "31",
    "OPE_QT_DIANOV": "30",
    "OPE_QT_DIADEZ": "31",
    "INT_VZ_MAXIMA": "0,24",
    "FIN_TFN_CD": "12",
    "FOU_TOU_CD": "null",
    "SIR_TSI_CD": "3",
    "SIR_TCT_CD": "1120",
    "SIR_AR_IRRIGADA": "0,00",
    "IUS_NU_ALTURARES": "",
    "IUS_AR_RESMAX": "",
    "IUS_VO_RESMAX": "",
    "EFL_QT_DBOBRUTO": "",
    "EFL_QT_DBOTRATADO": "",
    "EFL_QT_FOSFOROBRUTO": "",
    "EFL_QT_FOSFOROTRATADO": "",
    "EFL_QT_NITROGENIOBRUTO": "",
    "EFL_QT_NITROGENIOTRATADO": "",
    "ASB_DT_INSTALACAO": "",
    "ASB_TNP_CD": "null",
    "ASB_NU_DIAMETROPERFURACAO": "",
    "ASB_NU_DIAMETROFILTRO": "",
    "ASB_AQP_CD": "",
    "ASB_NU_TOPO": "",
    "ASB_NU_BASE": "",
    "ASB_TPN_CD": "null",
    "ASB_TCA_CD": "null",
    "ASB_NU_PROFUNDIDADEFINAL": "",
    "ASB_NU_ALTURABOCATUBO": "",
    "ASB_NU_COTATERRENO": "",
    "TST_DT": "",
    "TST_TTB_CD": "0",
    "TST_DS_TEMPODURACAO": "",
    "TST_NU_ND": "",
    "TST_NU_NE": "",
    "TST_VZ_ESTABILIZACAO": "",
    "TST_TMI_CD": "",
    "TST_NU_COEFICIENTEARMAZENAMENTO": "",
    "TST_NU_TRANSMISSIVIDADE": "",
    "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
    "TST_NU_PERMEABILIDADE": "",
    "AMA_DT_COLETA": "",
    "AMA_DT_ANALISE": "",
    "AMA_NU_CONDUTIVIDADEELETRICA": "",
    "AMA_QT_TEMPERATURA": "",
    "AMA_QT_STD": "",
    "AMA_QT_PH": "",
    "AMA_QT_COLIFORMESTOTAIS": "",
    "AMA_QT_COLIFORMESFECAIS": "",
    "AMA_QT_ BICARBONATO": "",
    "AMA_QT_ CALCIO": "",
    "AMA_QT_ CARBONATO": "",
    "AMA_QT_ CLORETO": "",
    "AMA_QT_ DUREZATOTAL": "",
    "AMA_QT_ FERROTOTAL": "",
    "AMA_QT_ FLUORETOS": "",
    "AMA_QT_ NITRATOS": "",
    "AMA_QT_ NITRITOS": "",
    "AMA_QT_ POTASSIO": "",
    "AMA_QT_ SODIO": "",
    "AMA_QT_ SULFATO": "",
    "AMA_QT_MAGNESIO": "",
    "INT_CD_ORIGEM": "14489",
    "INT_DS_OPCIONAL": ""
}

"OUT_DT_FINAL": "29/11/2058",
"OUT_DT_INICIAL": "24/01/2024",
"INT_CD_ORIGEM": "14490",
"EMP_NM_USUARIO": "SILVANY CAMBRAIA RODRIGUES DINIZ",

{
    "stateGrant": {
        "INT_TIN_CD": "1",
        "INT_TSU_CD": "2",
        "INT_TSI_CD": "",
        "INT_CR_LATITUDE": "-15,651047",
        "INT_CR_LONGITUDE": "-48,099645",
        "ING_NU_IBGEMUNICIPIO": "5300108",
        "EMP_NM_EMPREENDIMENTO": "NÚCLEO RURAL ALEXANDRE GUSMÃO, GLEBA 01, CHÁCARA 65",
        "EMP_NU_CPFCNPJ": "#12236918615",
        "EMP_NM_USUARIO": "SILVANY CAMBRAIA RODRIGUES DINIZ",
        "EMP_DS_EMAILRESPONSAVEL": "guimarodidiz@gmail.com",
        "EMP_NU_CEPENDERECO": "70754070",
        "EMP_DS_LOGRADOURO": "SQN 111, BLOCO G, APARTAMENTO 507, ASA NORTE",
        "EMP_DS_COMPLEMENTOENDERECO": "",
        "EMP_NU_LOGRADOURO": "",
        "EMP_NU_CAIXAPOSTAL": "0",
        "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
        "EMP_NU_DDD": "61",
        "EMP_NU_TELEFONE": "999714980",
        "OUT_TPO_CD": "7",
        "OUT_TSP_CD": "4",
        "OUT_DT_FINAL": "29/11/2058",
        "OUT_DT_INICIAL": "24/01/2024",
        "OUT_NU_PROCESSO": "00197-00004781/2023-47",
        "OUT_DS_ATO": "REGISTRO DE USO",
        "OUT_NU_ATO": "1159/2024",
        "INT_NU_SIAGAS": "",
        "OPE_VZ_MESJAN": "0,24",
        "OPE_VZ_MESFEV": "0,24",
        "OPE_VZ_MESMAR": "0,24",
        "OPE_VZ_MESABR": "0,24",
        "OPE_VZ_MESMAI": "0,24",
        "OPE_VZ_MESJUN": "0,24",
        "OPE_VZ_MESJUL": "0,24",
        "OPE_VZ_MESAGO": "0,24",
        "OPE_VZ_MESSET": "0,24",
        "OPE_VZ_MESOUT": "0,24",
        "OPE_VZ_MESNOV": "0,24",
        "OPE_VZ_MESDEZ": "0,24",
        "OPE_QT_HORASJAN": "5",
        "OPE_QT_HORASFEV": "5",
        "OPE_QT_HORASMAR": "5",
        "OPE_QT_HORASABR": "5",
        "OPE_QT_HORASMAI": "5",
        "OPE_QT_HORASJUN": "5",
        "OPE_QT_HORASJUL": "5",
        "OPE_QT_HORASAGO": "5",
        "OPE_QT_HORASSET": "5",
        "OPE_QT_HORASOUT": "5",
        "OPE_QT_HORASNOV": "5",
        "OPE_QT_HORASDEZ": "5",
        "OPE_QT_DIAJAN": "31",
        "OPE_QT_DIAFEV": "29",
        "OPE_QT_DIAMAR": "31",
        "OPE_QT_DIAABR": "30",
        "OPE_QT_DIAMAI": "31",
        "OPE_QT_DIAJUN": "30",
        "OPE_QT_DIAJUL": "31",
        "OPE_QT_DIAAGO": "31",
        "OPE_QT_DIASET": "30",
        "OPE_QT_DIAOUT": "31",
        "OPE_QT_DIANOV": "30",
        "OPE_QT_DIADEZ": "31",
        "INT_VZ_MAXIMA": "0,24",
        "FIN_TFN_CD": "6",
        "FOU_TOU_CD": "null",
        "SIR_TSI_CD": "3",
        "SIR_TCT_CD": "1120",
        "SIR_AR_IRRIGADA": "0,00",
        "IUS_NU_ALTURARES": "",
        "IUS_AR_RESMAX": "",
        "IUS_VO_RESMAX": "",
        "EFL_QT_DBOBRUTO": "",
        "EFL_QT_DBOTRATADO": "",
        "EFL_QT_FOSFOROBRUTO": "",
        "EFL_QT_FOSFOROTRATADO": "",
        "EFL_QT_NITROGENIOBRUTO": "",
        "EFL_QT_NITROGENIOTRATADO": "",
        "ASB_DT_INSTALACAO": "",
        "ASB_TNP_CD": "null",
        "ASB_NU_DIAMETROPERFURACAO": "",
        "ASB_NU_DIAMETROFILTRO": "",
        "ASB_AQP_CD": "",
        "ASB_NU_TOPO": "",
        "ASB_NU_BASE": "",
        "ASB_TPN_CD": "null",
        "ASB_TCA_CD": "null",
        "ASB_NU_PROFUNDIDADEFINAL": "12,00",
        "ASB_NU_ALTURABOCATUBO": "",
        "ASB_NU_COTATERRENO": "",
        "TST_DT": "",
        "TST_TTB_CD": "0",
        "TST_DS_TEMPODURACAO": "",
        "TST_NU_ND": "",
        "TST_NU_NE": "",
        "TST_VZ_ESTABILIZACAO": "",
        "TST_TMI_CD": "",
        "TST_NU_COEFICIENTEARMAZENAMENTO": "",
        "TST_NU_TRANSMISSIVIDADE": "",
        "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
        "TST_NU_PERMEABILIDADE": "",
        "AMA_DT_COLETA": "",
        "AMA_DT_ANALISE": "",
        "AMA_NU_CONDUTIVIDADEELETRICA": "",
        "AMA_QT_TEMPERATURA": "",
        "AMA_QT_STD": "",
        "AMA_QT_PH": "",
        "AMA_QT_COLIFORMESTOTAIS": "",
        "AMA_QT_COLIFORMESFECAIS": "",
        "AMA_QT_ BICARBONATO": "",
        "AMA_QT_ CALCIO": "",
        "AMA_QT_ CARBONATO": "",
        "AMA_QT_ CLORETO": "",
        "AMA_QT_ DUREZATOTAL": "",
        "AMA_QT_ FERROTOTAL": "",
        "AMA_QT_ FLUORETOS": "",
        "AMA_QT_ NITRATOS": "",
        "AMA_QT_ NITRITOS": "",
        "AMA_QT_ POTASSIO": "",
        "AMA_QT_ SODIO": "",
        "AMA_QT_ SULFATO": "",
        "AMA_QT_MAGNESIO": "",
        "INT_CD_ORIGEM": "14490",
        "INT_DS_OPCIONAL": ""
    }
}





21/11/2024 08:07 INSERIDO NOVAMENTEO PELO POSTMAN EM 8:56

"EMP_NU_CPFCNPJ": "#61817937120",
"EMP_NM_USUARIO": "FLÁVIO ROBERTO BENETTI",
"OUT_DT_FINAL": "10/07/2034",
"OUT_DT_INICIAL": "11/07/2024",
"OUT_NU_ATO": "0122/2024",
"INT_CD_ORIGEM": "14751",
"FIN_TFN_CD": "99",

[
    {
        "stateGrant": {
            "INT_TIN_CD": "1",
            "INT_TSU_CD": "2",
            "INT_TSI_CD": "",
            "INT_CR_LATITUDE": "-15,803110",
            "INT_CR_LONGITUDE": "-47,460308",
            "ING_NU_IBGEMUNICIPIO": "5300108",
            "EMP_NM_EMPREENDIMENTO": "NÚCLEO RURAL RIO PRETO, ÁREA RURAL LOTE 159",
            "EMP_NU_CPFCNPJ": "#61817937120",
            "EMP_NM_USUARIO": "FLÁVIO ROBERTO BENETTI",
            "EMP_DS_EMAILRESPONSAVEL": "contato@saggeo.com.br",
            "EMP_NU_CEPENDERECO": "73390200",
            "EMP_DS_LOGRADOURO": "NÚCLEO RURAL RIO PRETO, ÁREA RURAL LOTE 159",
            "EMP_DS_COMPLEMENTOENDERECO": "",
            "EMP_NU_LOGRADOURO": "",
            "EMP_NU_CAIXAPOSTAL": "0",
            "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
            "EMP_NU_DDD": "61",
            "EMP_NU_TELEFONE": "999888399",
            "OUT_TPO_CD": "1",
            "OUT_TSP_CD": "1",
            "OUT_DT_FINAL": "10/07/2034",
            "OUT_DT_INICIAL": "11/07/2024",
            "OUT_NU_PROCESSO": "00197-00004424/2023-89",
            "OUT_DS_ATO": "OUTORGA",
            "OUT_NU_ATO": "0122/2024",
            "INT_NU_SIAGAS": "",
            "OPE_VZ_MESJAN": "1,21",
            "OPE_VZ_MESFEV": "1,21",
            "OPE_VZ_MESMAR": "1,21",
            "OPE_VZ_MESABR": "1,21",
            "OPE_VZ_MESMAI": "1,21",
            "OPE_VZ_MESJUN": "1,21",
            "OPE_VZ_MESJUL": "1,21",
            "OPE_VZ_MESAGO": "1,21",
            "OPE_VZ_MESSET": "1,21",
            "OPE_VZ_MESOUT": "1,21",
            "OPE_VZ_MESNOV": "1,21",
            "OPE_VZ_MESDEZ": "1,21",
            "OPE_QT_HORASJAN": "1",
            "OPE_QT_HORASFEV": "1",
            "OPE_QT_HORASMAR": "1",
            "OPE_QT_HORASABR": "10",
            "OPE_QT_HORASMAI": "10",
            "OPE_QT_HORASJUN": "10",
            "OPE_QT_HORASJUL": "10",
            "OPE_QT_HORASAGO": "10",
            "OPE_QT_HORASSET": "10",
            "OPE_QT_HORASOUT": "10",
            "OPE_QT_HORASNOV": "1",
            "OPE_QT_HORASDEZ": "1",
            "OPE_QT_DIAJAN": "31",
            "OPE_QT_DIAFEV": "29",
            "OPE_QT_DIAMAR": "31",
            "OPE_QT_DIAABR": "30",
            "OPE_QT_DIAMAI": "31",
            "OPE_QT_DIAJUN": "30",
            "OPE_QT_DIAJUL": "31",
            "OPE_QT_DIAAGO": "31",
            "OPE_QT_DIASET": "30",
            "OPE_QT_DIAOUT": "31",
            "OPE_QT_DIANOV": "30",
            "OPE_QT_DIADEZ": "31",
            "INT_VZ_MAXIMA": "1,21",
            "FIN_TFN_CD": "99",
            "FOU_TOU_CD": "null",
            "SIR_TSI_CD": "3",
            "SIR_TCT_CD": "1120",
            "SIR_AR_IRRIGADA": "0,50",
            "IUS_NU_ALTURARES": "",
            "IUS_AR_RESMAX": "",
            "IUS_VO_RESMAX": "",
            "EFL_QT_DBOBRUTO": "",
            "EFL_QT_DBOTRATADO": "",
            "EFL_QT_FOSFOROBRUTO": "",
            "EFL_QT_FOSFOROTRATADO": "",
            "EFL_QT_NITROGENIOBRUTO": "",
            "EFL_QT_NITROGENIOTRATADO": "",
            "ASB_DT_INSTALACAO": "",
            "ASB_TNP_CD": "null",
            "ASB_NU_DIAMETROPERFURACAO": "",
            "ASB_NU_DIAMETROFILTRO": "",
            "ASB_AQP_CD": "",
            "ASB_NU_TOPO": "",
            "ASB_NU_BASE": "",
            "ASB_TPN_CD": "null",
            "ASB_TCA_CD": "null",
            "ASB_NU_PROFUNDIDADEFINAL": "90,00",
            "ASB_NU_ALTURABOCATUBO": "",
            "ASB_NU_COTATERRENO": "",
            "TST_DT": "",
            "TST_TTB_CD": "0",
            "TST_DS_TEMPODURACAO": "",
            "TST_NU_ND": "",
            "TST_NU_NE": "",
            "TST_VZ_ESTABILIZACAO": "",
            "TST_TMI_CD": "",
            "TST_NU_COEFICIENTEARMAZENAMENTO": "",
            "TST_NU_TRANSMISSIVIDADE": "",
            "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
            "TST_NU_PERMEABILIDADE": "",
            "AMA_DT_COLETA": "01/11/2023",
            "AMA_DT_ANALISE": "13/11/2023",
            "AMA_NU_CONDUTIVIDADEELETRICA": "109,2",
            "AMA_QT_TEMPERATURA": "",
            "AMA_QT_STD": "55",
            "AMA_QT_PH": "8",
            "AMA_QT_COLIFORMESTOTAIS": "",
            "AMA_QT_COLIFORMESFECAIS": "",
            "AMA_QT_ BICARBONATO": "",
            "AMA_QT_ CALCIO": "",
            "AMA_QT_ CARBONATO": "",
            "AMA_QT_ CLORETO": "2,72",
            "AMA_QT_ DUREZATOTAL": "57,14",
            "AMA_QT_ FERROTOTAL": "0,1",
            "AMA_QT_ FLUORETOS": "",
            "AMA_QT_ NITRATOS": "1,44",
            "AMA_QT_ NITRITOS": "0,38",
            "AMA_QT_ POTASSIO": "",
            "AMA_QT_ SODIO": "",
            "AMA_QT_ SULFATO": "",
            "AMA_QT_MAGNESIO": "",
            "INT_CD_ORIGEM": "14751",
            "INT_DS_OPCIONAL": ""
        }
    }
]














18/11/2024 9:36
INT_TIN_CD	INT_TSU_CD	INT_TSI_CD	INT_CR_LATITUDE	INT_CR_LONGITUDE	ING_NU_IBGEMUNICIPIO	EMP_NM_EMPREENDIMENTO	EMP_NU_CPFCNPJ	EMP_NM_USUARIO	EMP_DS_EMAILRESPONSAVEL	EMP_NU_CEPENDERECO	EMP_DS_LOGRADOURO	EMP_DS_COMPLEMENTOENDERECO	EMP_NU_LOGRADOURO	EMP_NU_CAIXAPOSTAL	EMP_CD_CODIGOIBGECORRESPONDENCIA	EMP_NU_DDD	EMP_NU_TELEFONE	OUT_TPO_CD	OUT_TSP_CD	OUT_DT_FINAL	OUT_DT_INICIAL	OUT_NU_PROCESSO	OUT_DS_ATO	OUT_NU_ATO	INT_NU_SIAGAS	OPE_VZ_MESJAN	OPE_VZ_MESFEV	OPE_VZ_MESMAR	OPE_VZ_MESABR	OPE_VZ_MESMAI	OPE_VZ_MESJUN	OPE_VZ_MESJUL	OPE_VZ_MESAGO	OPE_VZ_MESSET	OPE_VZ_MESOUT	OPE_VZ_MESNOV	OPE_VZ_MESDEZ	OPE_QT_HORASJAN	OPE_QT_HORASFEV	OPE_QT_HORASMAR	OPE_QT_HORASABR	OPE_QT_HORASMAI	OPE_QT_HORASJUN	OPE_QT_HORASJUL	OPE_QT_HORASAGO	OPE_QT_HORASSET	OPE_QT_HORASOUT	OPE_QT_HORASNOV	OPE_QT_HORASDEZ	OPE_QT_DIAJAN	OPE_QT_DIAFEV	OPE_QT_DIAMAR	OPE_QT_DIAABR	OPE_QT_DIAMAI	OPE_QT_DIAJUN	OPE_QT_DIAJUL	OPE_QT_DIAAGO	OPE_QT_DIASET	OPE_QT_DIAOUT	OPE_QT_DIANOV	OPE_QT_DIADEZ	INT_VZ_MAXIMA	FIN_TFN_CD	FOU_TOU_CD	SIR_TSI_CD	SIR_TCT_CD	SIR_AR_IRRIGADA	IUS_NU_ALTURARES	IUS_AR_RESMAX	IUS_VO_RESMAX	EFL_QT_DBOBRUTO	EFL_QT_DBOTRATADO	EFL_QT_FOSFOROBRUTO	EFL_QT_FOSFOROTRATADO	EFL_QT_NITROGENIOBRUTO	EFL_QT_NITROGENIOTRATADO	ASB_DT_INSTALACAO	ASB_TNP_CD	ASB_NU_DIAMETROPERFURACAO	ASB_NU_DIAMETROFILTRO	ASB_AQP_CD	ASB_NU_TOPO	ASB_NU_BASE	ASB_TPN_CD	ASB_TCA_CD	ASB_NU_PROFUNDIDADEFINAL	ASB_NU_ALTURABOCATUBO	ASB_NU_COTATERRENO	TST_DT	TST_TTB_CD	TST_DS_TEMPODURACAO	TST_NU_ND	TST_NU_NE	TST_VZ_ESTABILIZACAO	TST_TMI_CD	TST_NU_COEFICIENTEARMAZENAMENTO	TST_NU_TRANSMISSIVIDADE	TST_NU_CONDUTIVIDADEHIDRAULICA	TST_NU_PERMEABILIDADE	AMA_DT_COLETA	AMA_DT_ANALISE	AMA_NU_CONDUTIVIDADEELETRICA	AMA_QT_TEMPERATURA	AMA_QT_STD	AMA_QT_PH	AMA_QT_COLIFORMESTOTAIS	AMA_QT_COLIFORMESFECAIS	AMA_QT_ BICARBONATO	AMA_QT_ CALCIO	AMA_QT_ CARBONATO	AMA_QT_ CLORETO	AMA_QT_ DUREZATOTAL	AMA_QT_ FERROTOTAL	AMA_QT_ FLUORETOS	AMA_QT_ NITRATOS	AMA_QT_ NITRITOS	AMA_QT_ POTASSIO	AMA_QT_ SODIO	AMA_QT_ SULFATO	AMA_QT_MAGNESIO	INT_CD_ORIGEM	INT_DS_OPCIONAL	
1	2		-15,697862	-47,697143	5300108	ESTRADA DF 330, KM 08, VICINAL 09, GLEBA 232, S/N	#14636522168	ANTÔNIO CARLOS MATIAS DE SIQUEIRA

Já existe no sistema  



----------------------------------------------------------
----------------------------------------------------------
18/11/2024 10:47
NT_TIN_CD	INT_TSU_CD	INT_TSI_CD	INT_CR_LATITUDE	INT_CR_LONGITUDE	ING_NU_IBGEMUNICIPIO	EMP_NM_EMPREENDIMENTO	EMP_NU_CPFCNPJ	EMP_NM_USUARIO	EMP_DS_EMAILRESPONSAVEL	EMP_NU_CEPENDERECO	EMP_DS_LOGRADOURO	EMP_DS_COMPLEMENTOENDERECO	EMP_NU_LOGRADOURO	EMP_NU_CAIXAPOSTAL	EMP_CD_CODIGOIBGECORRESPONDENCIA	EMP_NU_DDD	EMP_NU_TELEFONE	OUT_TPO_CD	OUT_TSP_CD	OUT_DT_FINAL	OUT_DT_INICIAL	OUT_NU_PROCESSO	OUT_DS_ATO	OUT_NU_ATO	INT_NU_SIAGAS	OPE_VZ_MESJAN	OPE_VZ_MESFEV	OPE_VZ_MESMAR	OPE_VZ_MESABR	OPE_VZ_MESMAI	OPE_VZ_MESJUN	OPE_VZ_MESJUL	OPE_VZ_MESAGO	OPE_VZ_MESSET	OPE_VZ_MESOUT	OPE_VZ_MESNOV	OPE_VZ_MESDEZ	OPE_QT_HORASJAN	OPE_QT_HORASFEV	OPE_QT_HORASMAR	OPE_QT_HORASABR	OPE_QT_HORASMAI	OPE_QT_HORASJUN	OPE_QT_HORASJUL	OPE_QT_HORASAGO	OPE_QT_HORASSET	OPE_QT_HORASOUT	OPE_QT_HORASNOV	OPE_QT_HORASDEZ	OPE_QT_DIAJAN	OPE_QT_DIAFEV	OPE_QT_DIAMAR	OPE_QT_DIAABR	OPE_QT_DIAMAI	OPE_QT_DIAJUN	OPE_QT_DIAJUL	OPE_QT_DIAAGO	OPE_QT_DIASET	OPE_QT_DIAOUT	OPE_QT_DIANOV	OPE_QT_DIADEZ	INT_VZ_MAXIMA	FIN_TFN_CD	FOU_TOU_CD	SIR_TSI_CD	SIR_TCT_CD	SIR_AR_IRRIGADA	IUS_NU_ALTURARES	IUS_AR_RESMAX	IUS_VO_RESMAX	EFL_QT_DBOBRUTO	EFL_QT_DBOTRATADO	EFL_QT_FOSFOROBRUTO	EFL_QT_FOSFOROTRATADO	EFL_QT_NITROGENIOBRUTO	EFL_QT_NITROGENIOTRATADO	ASB_DT_INSTALACAO	ASB_TNP_CD	ASB_NU_DIAMETROPERFURACAO	ASB_NU_DIAMETROFILTRO	ASB_AQP_CD	ASB_NU_TOPO	ASB_NU_BASE	ASB_TPN_CD	ASB_TCA_CD	ASB_NU_PROFUNDIDADEFINAL	ASB_NU_ALTURABOCATUBO	ASB_NU_COTATERRENO	TST_DT	TST_TTB_CD	TST_DS_TEMPODURACAO	TST_NU_ND	TST_NU_NE	TST_VZ_ESTABILIZACAO	TST_TMI_CD	TST_NU_COEFICIENTEARMAZENAMENTO	TST_NU_TRANSMISSIVIDADE	TST_NU_CONDUTIVIDADEHIDRAULICA	TST_NU_PERMEABILIDADE	AMA_DT_COLETA	AMA_DT_ANALISE	AMA_NU_CONDUTIVIDADEELETRICA	AMA_QT_TEMPERATURA	AMA_QT_STD	AMA_QT_PH	AMA_QT_COLIFORMESTOTAIS	AMA_QT_COLIFORMESFECAIS	AMA_QT_ BICARBONATO	AMA_QT_ CALCIO	AMA_QT_ CARBONATO	AMA_QT_ CLORETO	AMA_QT_ DUREZATOTAL	AMA_QT_ FERROTOTAL	AMA_QT_ FLUORETOS	AMA_QT_ NITRATOS	AMA_QT_ NITRITOS	AMA_QT_ POTASSIO	AMA_QT_ SODIO	AMA_QT_ SULFATO	AMA_QT_MAGNESIO	INT_CD_ORIGEM	INT_DS_OPCIONAL	
1	2		-15,545020	-47,518518	5300108	NÚCLEO RURAL PIPIRIPAU 2, CHÁCARA 36	#26091012878	EDUARDO LUIS DO NASCIMENTO	centrosul.consultoria07@gmail.com	73000000	NÚCLEO RURAL PIPIRIPAU 2, CHÁCARA 36			0		61	999589994	1	1	27/02/2034	28/02/2024	00197-00003450/2023-90	OUTORGA	0001/2024		3,60	3,60	3,60	3,60	3,60	3,60	3,60	3,60	3,60	3,60	3,60	3,60	20	20	20	20	20	20	20	20


"EMP_NM_USUARIO": "EDUARDO LUIS DO NASCIMENTO",
"EMP_NU_CPFCNPJ": "#26091012878",
"OUT_DT_FINAL": "27/02/2034",
"OUT_DT_INICIAL": "28/02/2024",
"OUT_NU_ATO": "0001/2024",
"FIN_TFN_CD": "5",
"INT_CD_ORIGEM": "3015",


{

    "INT_TIN_CD": "1",
    "INT_TSU_CD": "2",
    "INT_TSI_CD": "",
    "INT_CR_LATITUDE": "-15,545020",
    "INT_CR_LONGITUDE": "-47,518518",
    "ING_NU_IBGEMUNICIPIO": "5300108",
    "EMP_NM_EMPREENDIMENTO": "NÚCLEO RURAL PIPIRIPAU 2, CHÁCARA 36",
    "EMP_NU_CPFCNPJ": "#26091012878",
    "EMP_NM_USUARIO": "EDUARDO LUIS DO NASCIMENTO",
    "EMP_DS_EMAILRESPONSAVEL": "centrosul.consultoria07@gmail.com",
    "EMP_NU_CEPENDERECO": "73000000",
    "EMP_DS_LOGRADOURO": "NÚCLEO RURAL PIPIRIPAU 2, CHÁCARA 36",
    "EMP_DS_COMPLEMENTOENDERECO": "",
    "EMP_NU_LOGRADOURO": "",
    "EMP_NU_CAIXAPOSTAL": "0",
    "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
    "EMP_NU_DDD": "61",
    "EMP_NU_TELEFONE": "999589994",
    "OUT_TPO_CD": "1",
    "OUT_TSP_CD": "1",
    "OUT_DT_FINAL": "27/02/2034",
    "OUT_DT_INICIAL": "28/02/2024",
    "OUT_NU_PROCESSO": "00197-00003450/2023-90",
    "OUT_DS_ATO": "OUTORGA",
    "OUT_NU_ATO": "0001/2024",
    "INT_NU_SIAGAS": "",
    "OPE_VZ_MESJAN": "3,60",
    "OPE_VZ_MESFEV": "3,60",
    "OPE_VZ_MESMAR": "3,60",
    "OPE_VZ_MESABR": "3,60",
    "OPE_VZ_MESMAI": "3,60",
    "OPE_VZ_MESJUN": "3,60",
    "OPE_VZ_MESJUL": "3,60",
    "OPE_VZ_MESAGO": "3,60",
    "OPE_VZ_MESSET": "3,60",
    "OPE_VZ_MESOUT": "3,60",
    "OPE_VZ_MESNOV": "3,60",
    "OPE_VZ_MESDEZ": "3,60",
    "OPE_QT_HORASJAN": "20",
    "OPE_QT_HORASFEV": "20",
    "OPE_QT_HORASMAR": "20",
    "OPE_QT_HORASABR": "20",
    "OPE_QT_HORASMAI": "20",
    "OPE_QT_HORASJUN": "20",
    "OPE_QT_HORASJUL": "20",
    "OPE_QT_HORASAGO": "20",
    "OPE_QT_HORASSET": "20",
    "OPE_QT_HORASOUT": "20",
    "OPE_QT_HORASNOV": "20",
    "OPE_QT_HORASDEZ": "20",
    "OPE_QT_DIAJAN": "31",
    "OPE_QT_DIAFEV": "29",
    "OPE_QT_DIAMAR": "31",
    "OPE_QT_DIAABR": "30",
    "OPE_QT_DIAMAI": "31",
    "OPE_QT_DIAJUN": "30",
    "OPE_QT_DIAJUL": "31",
    "OPE_QT_DIAAGO": "31",
    "OPE_QT_DIASET": "30",
    "OPE_QT_DIAOUT": "31",
    "OPE_QT_DIANOV": "30",
    "OPE_QT_DIADEZ": "31",
    "INT_VZ_MAXIMA": "3,60",
    "FIN_TFN_CD": "5",
    "FOU_TOU_CD": "null",
    "SIR_TSI_CD": "3",
    "SIR_TCT_CD": "1120",
    "SIR_AR_IRRIGADA": "0,00",
    "IUS_NU_ALTURARES": "",
    "IUS_AR_RESMAX": "",
    "IUS_VO_RESMAX": "",
    "EFL_QT_DBOBRUTO": "",
    "EFL_QT_DBOTRATADO": "",
    "EFL_QT_FOSFOROBRUTO": "",
    "EFL_QT_FOSFOROTRATADO": "",
    "EFL_QT_NITROGENIOBRUTO": "",
    "EFL_QT_NITROGENIOTRATADO": "",
    "ASB_DT_INSTALACAO": "",
    "ASB_TNP_CD": "null",
    "ASB_NU_DIAMETROPERFURACAO": "",
    "ASB_NU_DIAMETROFILTRO": "",
    "ASB_AQP_CD": "",
    "ASB_NU_TOPO": "0,00",
    "ASB_NU_BASE": "",
    "ASB_TPN_CD": "null",
    "ASB_TCA_CD": "null",
    "ASB_NU_PROFUNDIDADEFINAL": "0,00",
    "ASB_NU_ALTURABOCATUBO": "0,00",
    "ASB_NU_COTATERRENO": "",
    "TST_DT": "",
    "TST_TTB_CD": "0",
    "TST_DS_TEMPODURACAO": "",
    "TST_NU_ND": "0,0",
    "TST_NU_NE": "0,0",
    "TST_VZ_ESTABILIZACAO": "0,000",
    "TST_TMI_CD": "",
    "TST_NU_COEFICIENTEARMAZENAMENTO": "",
    "TST_NU_TRANSMISSIVIDADE": "",
    "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
    "TST_NU_PERMEABILIDADE": "",
    "AMA_DT_COLETA": "",
    "AMA_DT_ANALISE": "",
    "AMA_NU_CONDUTIVIDADEELETRICA": "0",
    "AMA_QT_TEMPERATURA": "0",
    "AMA_QT_STD": "0",
    "AMA_QT_PH": "0",
    "AMA_QT_COLIFORMESTOTAIS": "",
    "AMA_QT_COLIFORMESFECAIS": "",
    "AMA_QT_ BICARBONATO": "",
    "AMA_QT_ CALCIO": "",
    "AMA_QT_ CARBONATO": "",
    "AMA_QT_ CLORETO": "",
    "AMA_QT_ DUREZATOTAL": "",
    "AMA_QT_ FERROTOTAL": "",
    "AMA_QT_ FLUORETOS": "",
    "AMA_QT_ NITRATOS": "",
    "AMA_QT_ NITRITOS": "",
    "AMA_QT_ POTASSIO": "",
    "AMA_QT_ SODIO": "",
    "AMA_QT_ SULFATO": "",
    "AMA_QT_MAGNESIO": "",
    "INT_CD_ORIGEM": "3015",
    "INT_DS_OPCIONAL": ""
}


----------------------------------------------------------
----------------------------------------------------------
18/1/2024 11:58
"EMP_NM_USUARIO": "GENECY RODRIGUES MIRANDA",
"OUT_DT_FINAL": "21/01/2027",
"OUT_DT_INICIAL": "22/01/2024",
"FIN_TFN_CD": "5",
"INT_CD_ORIGEM": "13393",
[
    {
        "stateGrant": {
            "INT_TIN_CD": "1",
            "INT_TSU_CD": "2",
            "INT_TSI_CD": "",
            "INT_CR_LATITUDE": "-15,703952",
            "INT_CR_LONGITUDE": "-48,158491",
            "ING_NU_IBGEMUNICIPIO": "5300108",
            "EMP_NM_EMPREENDIMENTO": "NÚCLEO RURAL ALEXANDRE GUSMÃO, GLEBA 02, INCRA 06, RESERVA D, CHÁCARA TRÊS IRMÃOS",
            "EMP_NU_CPFCNPJ": "#83106464100",
            "EMP_NM_USUARIO": "GENECY RODRIGUES MIRANDA",
            "EMP_DS_EMAILRESPONSAVEL": "janajurema@yahoo.com.br",
            "EMP_NU_CEPENDERECO": "72799899",
            "EMP_DS_LOGRADOURO": "NÚCLEO RURAL ALEXANDRE GUSMÃO, GLEBA 02, INCRA 06, RESERVA D, CHÁCARA TRÊS IRMÃOS",
            "EMP_DS_COMPLEMENTOENDERECO": "",
            "EMP_NU_LOGRADOURO": "",
            "EMP_NU_CAIXAPOSTAL": "0",
            "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
            "EMP_NU_DDD": "61",
            "EMP_NU_TELEFONE": "999573386",
            "OUT_TPO_CD": "5",
            "OUT_TSP_CD": "1",
            "OUT_DT_FINAL": "21/01/2027",
            "OUT_DT_INICIAL": "22/01/2024",
            "OUT_NU_PROCESSO": "00197-00001307/2022-82",
            "OUT_DS_ATO": "OUTORGA PRÉVIA",
            "OUT_NU_ATO": "0449/2023",
            "INT_NU_SIAGAS": "",
            "OPE_VZ_MESJAN": "2,40",
            "OPE_VZ_MESFEV": "2,40",
            "OPE_VZ_MESMAR": "2,40",
            "OPE_VZ_MESABR": "2,40",
            "OPE_VZ_MESMAI": "2,40",
            "OPE_VZ_MESJUN": "2,40",
            "OPE_VZ_MESJUL": "2,40",
            "OPE_VZ_MESAGO": "2,40",
            "OPE_VZ_MESSET": "2,40",
            "OPE_VZ_MESOUT": "2,40",
            "OPE_VZ_MESNOV": "2,40",
            "OPE_VZ_MESDEZ": "2,40",
            "OPE_QT_HORASJAN": "20",
            "OPE_QT_HORASFEV": "20",
            "OPE_QT_HORASMAR": "20",
            "OPE_QT_HORASABR": "20",
            "OPE_QT_HORASMAI": "20",
            "OPE_QT_HORASJUN": "20",
            "OPE_QT_HORASJUL": "20",
            "OPE_QT_HORASAGO": "20",
            "OPE_QT_HORASSET": "20",
            "OPE_QT_HORASOUT": "20",
            "OPE_QT_HORASNOV": "20",
            "OPE_QT_HORASDEZ": "20",
            "OPE_QT_DIAJAN": "31",
            "OPE_QT_DIAFEV": "29",
            "OPE_QT_DIAMAR": "31",
            "OPE_QT_DIAABR": "30",
            "OPE_QT_DIAMAI": "31",
            "OPE_QT_DIAJUN": "30",
            "OPE_QT_DIAJUL": "31",
            "OPE_QT_DIAAGO": "31",
            "OPE_QT_DIASET": "30",
            "OPE_QT_DIAOUT": "31",
            "OPE_QT_DIANOV": "30",
            "OPE_QT_DIADEZ": "31",
            "INT_VZ_MAXIMA": "2,40",
            "FIN_TFN_CD": "5",
            "FOU_TOU_CD": "null",
            "SIR_TSI_CD": "3",
            "SIR_TCT_CD": "1120",
            "SIR_AR_IRRIGADA": "1,00",
            "IUS_NU_ALTURARES": "",
            "IUS_AR_RESMAX": "",
            "IUS_VO_RESMAX": "",
            "EFL_QT_DBOBRUTO": "",
            "EFL_QT_DBOTRATADO": "",
            "EFL_QT_FOSFOROBRUTO": "",
            "EFL_QT_FOSFOROTRATADO": "",
            "EFL_QT_NITROGENIOBRUTO": "",
            "EFL_QT_NITROGENIOTRATADO": "",
            "ASB_DT_INSTALACAO": "",
            "ASB_TNP_CD": "null",
            "ASB_NU_DIAMETROPERFURACAO": "",
            "ASB_NU_DIAMETROFILTRO": "",
            "ASB_AQP_CD": "",
            "ASB_NU_TOPO": "",
            "ASB_NU_BASE": "",
            "ASB_TPN_CD": "null",
            "ASB_TCA_CD": "null",
            "ASB_NU_PROFUNDIDADEFINAL": "",
            "ASB_NU_ALTURABOCATUBO": "",
            "ASB_NU_COTATERRENO": "",
            "TST_DT": "",
            "TST_TTB_CD": "0",
            "TST_DS_TEMPODURACAO": "",
            "TST_NU_ND": "",
            "TST_NU_NE": "",
            "TST_VZ_ESTABILIZACAO": "",
            "TST_TMI_CD": "",
            "TST_NU_COEFICIENTEARMAZENAMENTO": "",
            "TST_NU_TRANSMISSIVIDADE": "",
            "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
            "TST_NU_PERMEABILIDADE": "",
            "AMA_DT_COLETA": "",
            "AMA_DT_ANALISE": "",
            "AMA_NU_CONDUTIVIDADEELETRICA": "",
            "AMA_QT_TEMPERATURA": "",
            "AMA_QT_STD": "",
            "AMA_QT_PH": "",
            "AMA_QT_COLIFORMESTOTAIS": "",
            "AMA_QT_COLIFORMESFECAIS": "",
            "AMA_QT_ BICARBONATO": "",
            "AMA_QT_ CALCIO": "",
            "AMA_QT_ CARBONATO": "",
            "AMA_QT_ CLORETO": "",
            "AMA_QT_ DUREZATOTAL": "",
            "AMA_QT_ FERROTOTAL": "",
            "AMA_QT_ FLUORETOS": "",
            "AMA_QT_ NITRATOS": "",
            "AMA_QT_ NITRITOS": "",
            "AMA_QT_ POTASSIO": "",
            "AMA_QT_ SODIO": "",
            "AMA_QT_ SULFATO": "",
            "AMA_QT_MAGNESIO": "",
            "INT_CD_ORIGEM": "13393",
            "INT_DS_OPCIONAL": ""
        }
    }
]


-----------------------------------------------------------
-----------------------------------------------------------
12:00
"EMP_NM_USUARIO": "FERNANDO MENICUCCI NETO",
"OUT_DT_INICIAL": "22/01/2024",
"OUT_DT_FINAL": "21/01/2034",

"FIN_TFN_CD": "99",
"INT_CD_ORIGEM": "14435",

[
    {
        "stateGrant": {
            "INT_TIN_CD": "1",
            "INT_TSU_CD": "2",
            "INT_TSI_CD": "",
            "INT_CR_LATITUDE": "-15,855130",
            "INT_CR_LONGITUDE": "-47,883930",
            "ING_NU_IBGEMUNICIPIO": "5300108",
            "EMP_NM_EMPREENDIMENTO": "SHIS/QI 15, LOTE A, CHÁCARA 53",
            "EMP_NU_CPFCNPJ": "#50963554620",
            "EMP_NM_USUARIO": "FERNANDO MENICUCCI NETO",
            "EMP_DS_EMAILRESPONSAVEL": "fernando.menicuccineto63@gmail.com",
            "EMP_NU_CEPENDERECO": "70845080",
            "EMP_DS_LOGRADOURO": "SHIS/QI 15, LOTE A, CHÁCARA 53",
            "EMP_DS_COMPLEMENTOENDERECO": "",
            "EMP_NU_LOGRADOURO": "",
            "EMP_NU_CAIXAPOSTAL": "0",
            "EMP_CD_CODIGOIBGECORRESPONDENCIA": "",
            "EMP_NU_DDD": "61",
            "EMP_NU_TELEFONE": "992934472",
            "OUT_TPO_CD": "1",
            "OUT_TSP_CD": "1",
            "OUT_DT_FINAL": "21/01/2034",
            "OUT_DT_INICIAL": "22/01/2024",
            "OUT_NU_PROCESSO": "00197-00003273/2023-41",
            "OUT_DS_ATO": "OUTORGA",
            "OUT_NU_ATO": "0452/2023",
            "INT_NU_SIAGAS": "",
            "OPE_VZ_MESJAN": "0,00",
            "OPE_VZ_MESFEV": "0,00",
            "OPE_VZ_MESMAR": "0,00",
            "OPE_VZ_MESABR": "0,40",
            "OPE_VZ_MESMAI": "0,40",
            "OPE_VZ_MESJUN": "0,40",
            "OPE_VZ_MESJUL": "0,40",
            "OPE_VZ_MESAGO": "0,40",
            "OPE_VZ_MESSET": "0,40",
            "OPE_VZ_MESOUT": "0,40",
            "OPE_VZ_MESNOV": "0,00",
            "OPE_VZ_MESDEZ": "0,00",
            "OPE_QT_HORASJAN": "0",
            "OPE_QT_HORASFEV": "0",
            "OPE_QT_HORASMAR": "0",
            "OPE_QT_HORASABR": "10",
            "OPE_QT_HORASMAI": "10",
            "OPE_QT_HORASJUN": "10",
            "OPE_QT_HORASJUL": "10",
            "OPE_QT_HORASAGO": "10",
            "OPE_QT_HORASSET": "10",
            "OPE_QT_HORASOUT": "10",
            "OPE_QT_HORASNOV": "0",
            "OPE_QT_HORASDEZ": "0",
            "OPE_QT_DIAJAN": "31",
            "OPE_QT_DIAFEV": "29",
            "OPE_QT_DIAMAR": "31",
            "OPE_QT_DIAABR": "30",
            "OPE_QT_DIAMAI": "31",
            "OPE_QT_DIAJUN": "30",
            "OPE_QT_DIAJUL": "31",
            "OPE_QT_DIAAGO": "31",
            "OPE_QT_DIASET": "30",
            "OPE_QT_DIAOUT": "31",
            "OPE_QT_DIANOV": "30",
            "OPE_QT_DIADEZ": "31",
            "INT_VZ_MAXIMA": "0,40",
            "FIN_TFN_CD": "99",
            "FOU_TOU_CD": "null",
            "SIR_TSI_CD": "3",
            "SIR_TCT_CD": "1120",
            "SIR_AR_IRRIGADA": "0,15",
            "IUS_NU_ALTURARES": "",
            "IUS_AR_RESMAX": "",
            "IUS_VO_RESMAX": "",
            "EFL_QT_DBOBRUTO": "",
            "EFL_QT_DBOTRATADO": "",
            "EFL_QT_FOSFOROBRUTO": "",
            "EFL_QT_FOSFOROTRATADO": "",
            "EFL_QT_NITROGENIOBRUTO": "",
            "EFL_QT_NITROGENIOTRATADO": "",
            "ASB_DT_INSTALACAO": "",
            "ASB_TNP_CD": "null",
            "ASB_NU_DIAMETROPERFURACAO": "",
            "ASB_NU_DIAMETROFILTRO": "",
            "ASB_AQP_CD": "",
            "ASB_NU_TOPO": "",
            "ASB_NU_BASE": "",
            "ASB_TPN_CD": "null",
            "ASB_TCA_CD": "null",
            "ASB_NU_PROFUNDIDADEFINAL": "",
            "ASB_NU_ALTURABOCATUBO": "",
            "ASB_NU_COTATERRENO": "",
            "TST_DT": "",
            "TST_TTB_CD": "0",
            "TST_DS_TEMPODURACAO": "",
            "TST_NU_ND": "",
            "TST_NU_NE": "",
            "TST_VZ_ESTABILIZACAO": "",
            "TST_TMI_CD": "",
            "TST_NU_COEFICIENTEARMAZENAMENTO": "",
            "TST_NU_TRANSMISSIVIDADE": "",
            "TST_NU_CONDUTIVIDADEHIDRAULICA": "",
            "TST_NU_PERMEABILIDADE": "",
            "AMA_DT_COLETA": "",
            "AMA_DT_ANALISE": "",
            "AMA_NU_CONDUTIVIDADEELETRICA": "",
            "AMA_QT_TEMPERATURA": "",
            "AMA_QT_STD": "",
            "AMA_QT_PH": "",
            "AMA_QT_COLIFORMESTOTAIS": "",
            "AMA_QT_COLIFORMESFECAIS": "",
            "AMA_QT_ BICARBONATO": "",
            "AMA_QT_ CALCIO": "",
            "AMA_QT_ CARBONATO": "",
            "AMA_QT_ CLORETO": "",
            "AMA_QT_ DUREZATOTAL": "",
            "AMA_QT_ FERROTOTAL": "",
            "AMA_QT_ FLUORETOS": "",
            "AMA_QT_ NITRATOS": "",
            "AMA_QT_ NITRITOS": "",
            "AMA_QT_ POTASSIO": "",
            "AMA_QT_ SODIO": "",
            "AMA_QT_ SULFATO": "",
            "AMA_QT_MAGNESIO": "",
            "INT_CD_ORIGEM": "14435",
            "INT_DS_OPCIONAL": ""
        }
    }
]